# Generated by Django 5.0 on 2024-01-09 11:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_serv', '0022_usuario_is_superusuario'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos que este usuário pertence. Um usuário terá todas as permissões concedidas a cada um dos seus grupos.', related_name='usuarios', related_query_name='usuario', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='usuarios', related_query_name='usuario', to='auth.permission', verbose_name='permissões do usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
